### ISSUE TITLE
Environmental settings are on same line as language

### ISSUE THREAD

**Issue by nschonni** [sarahhodne/travis-lite#14]
Ex1: http://travis-lite.com/gedankenstuecke/snpr/jobs/4545252
`Language: 1.9.2 DB=postgres CI=1`

Ex2: http://travis-lite.com/nschonni/wet-boew/jobs/4544304
`Language: java SECURE lyMMmGvleOhoAD+T/UQqFfjjiAW+WWU+9YqZjLEfVQxgOQKxB1/GXs45WXko B6sQ/U6+b5V202h3RwKuxUUgWZ1TMSrfWjy5NTX+tM8y5IJaVGh4Dl+9p51o ekfMtEQ6TUHTFpLFwouaGpf4DUCpJHUtoh8HoI/kuAdnIpVmpMY=`

**Comment by sarahhodne** [comment]
This appears to be fixed now, although we have a new issue where some builds don't have a language. Closing this.
