### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by fulldecent** [sarahhodne/travis-lite#22]
Seeing this error for every build page.

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

![screen shot 2014-10-06 at 10 42 30 am](https://cloud.githubusercontent.com/assets/382183/4527392/0832c376-4d67-11e4-82a0-be9149c8e45c.png)

**Comment by fulldecent** [comment]
Example URL http://travis-lite.com/Spectingular/spectingular.js/builds/37854533

**Comment by jmoody** [comment]
http://travis-lite.com/

Now points to 'Heroku | Welcome to your new app'
